#!/bin/sh

### BEGIN INIT INFO
# Provides:		virgo
# Required-Start:	$local_fs $network
# Required-Stop:	$local_fs $network
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Eclipse Virgo
# Description:		OSGi runtime environment
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

VIRGO_USER=virgo
VIRGO_HOME=/opt/virgo
VIRGO_OPTS=

if [ -r /etc/default/virgo ]; then
	. /etc/default/virgo
fi

case "${1}" in
  start)
	exec start-stop-daemon --start --background --chuid $VIRGO_USER \
		--exec /usr/bin/authbind -- \
		--deep "$VIRGO_HOME/opt/bin/startup.sh" $VIRGO_OPTS
  ;;

  stop)
	exec $VIRGO_HOME/bin/shutdown.sh
  ;;
 
  restart)
	exec ${0} stop
	exec ${0} start
  ;;

  *)
	echo "Usage: `basename ${0}` {start|stop|restart}"
	exit 0
  ;;
esac
